insert into curso (id, nombre, tutor) values (NEXTVAL('hibernate_sequence'), '1º DAM', 'Miguel Campos');
insert into curso (id, nombre, tutor) values (NEXTVAL('hibernate_sequence'), '2º DAM', 'Luis Miguel López');

insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Mosdall', 'Hengoed', 'Quintus', 'qhengoed0@dedecms.com', '1972-03-23', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Midgley', 'Sever', 'Matti', 'msever1@examiner.com', '1901-12-26', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Issakov', 'Britch', 'Karry', 'kbritch2@technorati.com', '1988-10-20', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Volks', 'Jacob', 'Tiffanie', 'tjacob3@soundcloud.com', '1921-02-25', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Govey', 'Duddle', 'Olvan', 'oduddle4@epa.gov', '1922-01-04', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Tuting', 'Millen', 'Fabiano', 'fmillen5@pinterest.com', '1907-07-29', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Bogaert', 'Losbie', 'Sigrid', 'slosbie6@rakuten.co.jp', '1974-03-10', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Burnall', 'Castagnaro', 'Carol', 'ccastagnaro7@icio.us', '1974-02-18', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Bodle', 'Penbarthy', 'Herminia', 'hpenbarthy8@360.cn', '1913-07-22', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'De Giorgi', 'Baldini', 'Willi', 'wbaldini9@cbslocal.com', '1949-10-12', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Jeanenet', 'Kinmond', 'Franni', 'fkinmonda@wix.com', '1981-02-21', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Tidd', 'Goude', 'Rockwell', 'rgoudeb@ft.com', '1946-11-18', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Lemmon', 'Magnay', 'Philippa', 'pmagnayc@hugedomains.com', '1995-03-06', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Itzkowicz', 'Minshaw', 'Graeme', 'gminshawd@wordpress.com', '1901-10-23', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Lynch', 'Fellow', 'Theresa', 'tfellowe@gnu.org', '1959-06-16', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Meth', 'Roscrigg', 'Kettie', 'kroscriggf@cbslocal.com', '1998-03-27', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Malcolmson', 'Wyldbore', 'Elvina', 'ewyldboreg@360.cn', '1986-07-09', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Haywood', 'Broadhurst', 'Kara', 'kbroadhursth@examiner.com', '1935-09-18', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Blennerhassett', 'Boole', 'Hettie', 'hboolei@cbsnews.com', '1990-05-12', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Macon', 'MacGaughie', 'Joseito', 'jmacgaughiej@mediafire.com', '1905-11-19', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Parkyn', 'Mithan', 'Reena', 'rmithank@ftc.gov', '1955-06-18', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Smitherman', 'Gumery', 'Faythe', 'fgumeryl@dell.com', '1989-07-23', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Grinnov', 'Pigram', 'Whittaker', 'wpigramm@microsoft.com', '1985-06-26', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Biggs', 'Bartolomeo', 'Phaidra', 'pbartolomeon@joomla.org', '1980-11-23', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Mattityahou', 'Rylance', 'Clarissa', 'crylanceo@stumbleupon.com', '1997-04-25', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Lempke', 'Syvret', 'Elly', 'esyvretp@amazon.co.uk', '1997-12-07', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Slatten', 'Attock', 'Nanette', 'nattockq@google.nl', '1921-05-21', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Silverwood', 'Skerratt', 'Aldrich', 'askerrattr@usda.gov', '1905-04-12', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Staten', 'Allain', 'Valerye', 'vallains@parallels.com', '1929-06-01', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Baildon', 'Cuxon', 'Perri', 'pcuxont@businessweek.com', '1927-04-07', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Ridge', 'Tadman', 'Rickard', 'rtadmanu@geocities.jp', '1977-04-28', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Barge', 'Voelker', 'Darbie', 'dvoelkerv@alexa.com', '1946-04-08', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Godwin', 'Dwelling', 'Kathi', 'kdwellingw@google.co.jp', '1933-11-24', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'O''Beirne', 'Ahlin', 'Bartram', 'bahlinx@amazon.de', '1936-07-27', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Dudney', 'Ullett', 'Melinde', 'mulletty@economist.com', '1964-10-07', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Brobeck', 'Raffels', 'Buckie', 'braffelsz@123-reg.co.uk', '1949-05-04', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Duffy', 'Alcock', 'Lily', 'lalcock10@cocolog-nifty.com', '1945-01-27', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Orwell', 'Iacopetti', 'Valentino', 'viacopetti11@google.ca', '1996-02-12', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Measor', 'Gavey', 'Basil', 'bgavey12@craigslist.org', '1938-07-17', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Plunket', 'Folomin', 'Carena', 'cfolomin13@scribd.com', '1990-12-15', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'O''Donegan', 'Froud', 'Meade', 'mfroud14@odnoklassniki.ru', '2000-05-27', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Ottam', 'Hicks', 'Verney', 'vhicks15@mayoclinic.com', '1954-06-16', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Cortin', 'Iacovini', 'Joya', 'jiacovini16@delicious.com', '1999-04-11', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'De Michetti', 'Tsarovic', 'Gerard', 'gtsarovic17@sina.com.cn', '1917-02-02', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Delacoste', 'Aburrow', 'Rhett', 'raburrow18@yandex.ru', '1917-04-13', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Rusk', 'Mc Kellen', 'Isadore', 'imckellen19@ezinearticles.com', '2001-04-05', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Elintune', 'Vanns', 'Iolande', 'ivanns1a@blogger.com', '1964-08-06', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Lidbetter', 'Dorkens', 'Randi', 'rdorkens1b@accuweather.com', '1957-10-04', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Sille', 'Truesdale', 'Justinn', 'jtruesdale1c@wunderground.com', '1976-05-12', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Don', 'Aliberti', 'Cal', 'caliberti1d@cbslocal.com', '1956-07-05', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Andreotti', 'Aggett', 'Payton', 'paggett1e@tinyurl.com', '1980-05-05', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Germon', 'Keyson', 'Nicoli', 'nkeyson1f@mozilla.org', '1962-07-20', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'MacRory', 'McGuiney', 'Ingrid', 'imcguiney1g@un.org', '1910-05-15', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Jeavons', 'Fison', 'Thor', 'tfison1h@hp.com', '1910-08-04', 1);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Hofer', 'Downes', 'Cletus', 'cdownes1i@gov.uk', '1929-09-13', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Whyatt', 'Spinelli', 'Sophronia', 'sspinelli1j@apple.com', '1937-04-14', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Fassmann', 'McCook', 'Petr', 'pmccook1k@bandcamp.com', '1958-11-29', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Partener', 'Bonnick', 'Maure', 'mbonnick1l@opera.com', '1913-09-28', 2);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Kilfedder', 'Strodder', 'Carney', 'cstrodder1m@miitbeian.gov.cn', '1979-06-06', null);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Bourgourd', 'Larkby', 'Avigdor', 'alarkby1n@ezinearticles.com', '1914-08-30', null);
insert into ALUMNO (id, apellido1, apellido2, nombre, email, fecha_nacimiento, curso_id) values (NEXTVAL('hibernate_sequence'), 'Bourgourd', 'Larkby', 'Ivor', 'ilarkby@ezinearticles.com', '1928-08-30', null);
